### ISSUE TITLE
 about extract code

### ISSUE THREAD

**Issue by wjourney** [cs-heibao/PFPNet_Pytorch#1]
why the trained model's extract code: fh9uby is wrong?

**Comment by cs-heibao** [comment]
@wjourney 
maybe something is wrong, and here is the new link
 https://pan.baidu.com/s/1neST11wHXB2Hmouf6ucaEw code: spw6

**Comment by wjourney** [comment]
Thank you very much for your reply. I plan to reproduce this code. May I ask whether this code can be completely reproduced and whether the accuracy is consistent with the original paper

**Comment by cs-heibao** [comment]
I've not do the detail test and my project has only one class, so I don't compare the accuracy with the original paper.
the network structure is clear, you can try to reproduce
